add kafka+CDC+debezium,vẫn còn lỗi deadlock

diff --git a/source/docker-compose.yml b/source/docker-compose.yml
--- a/source/docker-compose.yml
+++ b/source/docker-compose.yml
@@ -1,5 +1,5 @@
 version: "3.9"
-
+#Lệnh chạy lại docker compose up -d --build
 services:
   backend:
     build: ./server/WeChat        
@@ -9,13 +9,12 @@ services:
     depends_on:
       - redis
     environment:
-      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/ChatMe
+      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ChatMe
       - SPRING_DATASOURCE_USERNAME=root
       - SPRING_DATASOURCE_PASSWORD=admin
       - SPRING_DATA_REDIS_HOST=redis
       - SPRING_DATA_REDIS_PORT=6379
       - CENTRIFUGO_API_URL=http://centrifugo:8000
-
     restart: unless-stopped
 
   frontend:
@@ -61,9 +60,90 @@ services:
     ports:
       - "6379:6379"
     volumes:
-      - cache:/data
+      - redis-data:/data
     restart: unless-stopped
 
+  mysql:
+    image: mysql:8.0
+    container_name: mysql
+    restart: unless-stopped
+    environment:
+      MYSQL_ROOT_PASSWORD: admin           # giống password bạn đang dùng
+      MYSQL_DATABASE: ChatMe              # tên DB
+    ports:
+      - "3307:3306"                       # mở cổng ra ngoài để bạn còn connect từ DBeaver / MySQL Workbench
+    command:
+      [
+        "mysqld",
+        "--server-id=1",
+        "--log_bin=mysql-bin",
+        "--binlog_format=ROW",
+        "--binlog_row_image=FULL"
+      ]
+    volumes:
+      - mysql-data:/var/lib/mysql         # lưu data MySQL ra volume
+
+  kafka:
+    image: bitnamilegacy/kafka:3.7.0   #Hỗ trợ Kraft(Không cần ZooKeeper)
+    container_name: kafka        #Tên container
+    hostname: kafka              #Hostname để container khác gọi bằng kafka
+    ports:
+      - "9094:9094"        # dùng cổng này để debug từ máy host
+    environment:
+      - KAFKA_CFG_NODE_ID=0       #Id của node Kafka trong cluster (node 0)
+      - KAFKA_CFG_PROCESS_ROLES=controller,broker       #Node này vừa làm controller(quản lý metadata) vừa làm broker(xử lý message)
+      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093      #Chỉ định danh sách controller quorum (1 node: id=0, host=kafka, port = 9093)
+      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094    
+            #PLAINTEXT-9092: cho docker internal (connect,centrifugo,...)
+            #CONTROLLER-9093: cho controller nội bộ KRaft
+            #EXTERNAL-9094: để máy thật truy cập qua 9094
+      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094  
+            #Kafka quảng cáo đại chỉ
+            #-PLAINTEXT cho container khác --> kafka:9092
+            #-EXTERNAL cho máy host -->localhost:9094
+      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT   #Tất cả listener dùng giao thức PLAINTEXT
+      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER #Listener nào dùng cho controller (CONTROLLER://:9093)
+      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true   #Tự tạo topic nếu producer/consumer sử dụng topic chưa tồn tại (tiện cho dev)
+    volumes:
+      - kafka-data:/tmp/kraft-combined-logs    #Volume để Kafka lưu metadata + logs,tránh mất dữ liệu khi restart
+
+  connect:          #Service Kafka connect
+    image: quay.io/debezium/connect:2.5     #Image connect đã tích hợp debezium
+    container_name: connect            #Tên container
+    depends_on: 
+      - kafka        # Chạy sau khi kafka start
+      - mysql        # Chạy sau khi mysql start(Debezium cần connect DB)
+    ports:
+      - "8083:8083"  # Kafka Connect REST API (dùng để tạo connector)
+    environment:
+      BOOTSTRAP_SERVERS: kafka:9092  #Kafka broker để kết nối (Listener PLAINTEXT nội bộ)
+      GROUP_ID: 1       #ID cho cluster connect (1 node nên cứ để 1) 
+      CONFIG_STORAGE_TOPIC: connect_configs      #Topic để lưu confid connector
+      OFFSET_STORAGE_TOPIC: connect_offsets      #Topic lưu offset binlog đã đọc tới đâu của Debezium
+      STATUS_STORAGE_TOPIC: connect_statuses     #Topic lưu trạng thái connector (running,failed)
+  
+  connect-config-loader:   #Container phụ chỉ chạy 1 lần để nạp Debezium
+    image: curlimages/curl:8.8.0         #Image nhẹ chỉ chưa curl để gọi REST API
+    container_name: connect-config-loader
+    depends_on:
+      - connect          #Chờ connect sẵn sàng
+    volumes:
+      - ./debezium/debezium-config.json:/debezium-config.json #Mount file config Debezium từ máy bạn vào container
+    entrypoint: >  #Đợi Kafka connect chạy xong,xóa connector cũ nếu tồn tại,tạo connector mới bằng file Debezium,kết thúc nhiệm vụ và container tắt
+      sh -c "
+        echo 'Waiting for Kafka Connect to start...';    
+        until curl -sf http://connect:8083/connectors; do sleep 2; done;
+        echo 'Kafka Connect is up, posting Debezium connector config...';
+        # xoá connector cũ nếu có
+        curl -s -X DELETE http://connect:8083/connectors/grandchat-connector || true;
+        # tạo mới
+        curl -s -X POST -H 'Content-Type: application/json' --data @/debezium-config.json http://connect:8083/connectors;
+        echo 'Debezium connector configured.';
+      "
 volumes:
-  cache:
+  kafka-data:           # Kafka dùng để lưu logs KRaft
+    driver: local
+  redis-data:           # để Redis mount vào /data (thay vì cache)
+    driver: local
+  mysql-data:           # để MySQL lưu data
     driver: local
